version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-rails_micro_blog}
      - MYSQL_USER=${DB_USERNAME:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
  app:
    build:
      context: .
      dockerfile: ./infra/docker/app/Dockerfile
    volumes:
      - "./backend:/workspace"
    depends_on:
      - db
    environment:
      DATABASE_NAME: rails_micro_blog
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: secret
      RAILS_ENV: development
  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
volumes:
  db-store: